# Site settings
name: Jamilu Salisu
title: Jamilu Salisu | Software Engineer
description: Jamilu Salisu is a highly motivated software developer with solid understanding of software development best practices. I'm also an open source hobbyist & a community mentor keen to change-makers.👨‍
url: https://Jamilusalis.github.io
baseurl: ""
email: jamilusalis@gmail.com
keywords: jamilu salisu, engineer, software engineer, computer science, jamilusalis, jamilu
cover: #
logo: #
resume: #
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jamilusalis
  - title: twitter
    url: https://twitter.com/jamilusalism
  - title: github
    url: https://github.com/jamilusalis

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
