# Site settings
name: Timothy Olaleke
title: Kelvin Kamau | Software Engineer
description: Timothy Olaleke is a highly motivated software developer with solid understanding of software development best practices. I'm also an open source hobbyist & a community mentor keen to change-makers.👨‍
url: https://www.kelvinkamau.app
baseurl: ""
email: chat@kelvinkamau.app
keywords: kelvin kamau, engineer, software engineer, computer science, kelvin, kamau, wachira
cover: https://www.kelvinkamau.app/og.png
logo: https://www.kelvinkamau.app/img/icon.png
resume: https://www.kelvinkamau.app
social:
  - title: twitter
    url: https://twitter.com/kamaucodes
  - title: instagram
    url: https://instagram.com/justkeykay
  - title: github
    url: https://github.com/kelvinkamau
  - title: linkedin
    url: https://www.linkedin.com/in/kelvinkamau
  - title: terms
    url: https://www.kelvinkamau.app/terms/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
