# Site settings
name: Jamilu Salisu
title: Jamilu Salisu | Software Engineer
description: Jamilu Salisu is a highly motivated software, web and mobile development with solid understanding of development best practices. I am Self taught programmer, I've been building complex web applications since 2015 and standalone application since 2017.👨‍
url: https://Jamilusalis.github.io
baseurl: ""
email: jamilusalis@gmail.com
keywords: jamilu salisu, jamilusalis, jamilusalism, engineer, software engineer, computer science, jamilu, salisu, salis, web developer, mobile developer, software developer
cover: https://github.com/Jamilusalis/jamilusalis.github.io/blob/master/Jamilusalis.JPG
logo: https://github.com/Jamilusalis/jamilusalis.github.io/blob/master/Jamilusalis.JPG
resume: #
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jamilusalism
  - title: twitter
    url: https://twitter.com/jamilusalism
  - title: facebook	
    url: https://facebook.com/Jamilusalism
  - title: telegram
    url: https://t.me/jamilusalism
  - title: whatsapp	
    url: https://wa.me/2348028752833
  - title: instagram
    url: https://github.com/jamilusalis
  - title: pinterest
    url: https://www.pinterest.com/jamilusalism   
  - title: github
    url: https://github.com/jamilusalis

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap

theme: jekyll-theme-cayman
